name: Build

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    env:
      THEOS: ${{ github.workspace }}/theos
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Theos
        uses: actions/cache@v4
        with:
          path: ${{ env.THEOS }}
          key: ${{ runner.os }}-theos-${{ hashFiles('.github/workflows/build.yml') }}
          
      - name: Install Theos
        if: steps.cache-theos.outputs.cache-hit != 'true'
        run: git clone --recursive https://github.com/theos/theos.git ${{ env.THEOS }}
          
      - name: Cache SDKs
        uses: actions/cache@v4
        with:
          path: ${{ env.THEOS }}/sdks
          key: ${{ runner.os }}-theos-sdks-iPhoneOS16.5
          
      - name: Download iOS SDK
        if: steps.cache-sdks.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{ env.THEOS }}/sdks
          curl -L -o sdk.tar.xz https://github.com/theos/sdks/releases/download/master-146e41f/iPhoneOS16.5.sdk.tar.xz
          tar -xJf sdk.tar.xz -C ${{ env.THEOS }}/sdks
          rm sdk.tar.xz
          
      - name: Install build deps
        run: brew install ldid make
          
      - name: Build
        run: |
          export PATH="$(brew --prefix make)/libexec/gnubin:$PATH"
          make package
          
      - name: Upload .deb
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: JQYSAdAuto-deb
          path: packages/*.deb
